version: '3.8'

services:

  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  kibana:
    container_name: kib
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      ES_HOST: elasticsearch
      INDEX_NAME: tweets
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch